# Generated by Django 5.1.1 on 2024-09-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_videoads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ads_images/')),
            ],
        ),
    ]
