# Generated by Django 5.1.1 on 2024-09-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_imageads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
