# Generated by Django 5.1.1 on 2024-10-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_newsarticle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonews',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualstory',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
