# Generated by Django 5.1.1 on 2024-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_imageads_image_alter_newsarticle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_articles',
            field=models.ManyToManyField(blank=True, to='app.newsarticle'),
        ),
    ]
